# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/core"
    schedule:
      #interval: weekly
      #day: monday
      interval: "daily"
      # Check for updates at noon UTC (5am PDT/4am PST)
      time: "12:00"
    open-pull-requests-limit: 5
    reviewers:
      - roverwolf
    # Ignore dev dependencies that match what composer would update
    # as we care more about non-dev dependencies,
    # but notification of major upgrades to dev dependencies is good
    ignore:
      - dependency-name: roave/security-advisories
      - dependency-name: symplify/easy-coding-standard
        versions: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: escapestudios/symfony2-coding-standard
        versions: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "codeception/*"
        versions: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: ericmartel/codeception-email-mailtrap
        versions: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: softcreatr/jsonpath
        versions: ["version-update:semver-patch"]
      - dependency-name: league/factory-muffin
        versions: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: league/factory-muffin-faker
        versions: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: phpunit/phpunit
      - dependency-name: vlucas/phpdotenv
        versions: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: symfony/maker-bundle
        versions: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: symfony/phpunit-bridge
      - dependency-name: jetbrains/phpstorm-attributes
        versions: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "symfony/*"
        versions: ["version-update:semver-major", "version-update:semver-minor"]
      # Also ignore aws-sdk-php at it updates frequently but doesn't affect much
      - dependency-name: aws/aws-sdk-php
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
