simple_things_entity_audit:
    #entity_manager: default
    table_prefix: 'audit_'
    table_suffix: ''
    #revision_field_name: rev
    #revision_type_field_name: revtype
    revision_table_name: audit_revision
    #revision_id_field_type: integer
    audited_entities:
        - App\Entity\Framework\LsDoc
        - App\Entity\Framework\LsDocAttribute
        - App\Entity\Framework\LsDocSubject
        - App\Entity\Framework\LsItem
        - App\Entity\Framework\LsItemConcept
        - App\Entity\Framework\LsAssociation
        - App\Entity\Framework\LsDefAssociationGrouping
        - App\Entity\Framework\LsDefItemType
        - App\Entity\Framework\LsDefConcept
        - App\Entity\Framework\LsDefGrade
        - App\Entity\Framework\LsDefLicence
        - App\Entity\Framework\LsDefSubject
        - App\Entity\Framework\CfRubric
        - App\Entity\Framework\CfRubricCriterion
        - App\Entity\Framework\CfRubricCriterionLevel
        - App\Entity\User\Organization
        - App\Entity\User\User
        - App\Entity\User\UserDocAcl
        - App\Entity\ChangeEntry
    global_ignore_columns:
        - password
