swiftmailer:
    spool: { type: 'memory' }
    #url: '%env(MAILER_URL)%'
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    auth_mode: "%mailer_auth_mode%"
    port:      "%mailer_port%"
    # to disable mail uncomment disable_delivery: true
    # disable_delivery: true
