doctrine:
    orm:
        auto_generate_proxy_classes: false
        entity_managers:
            default:
                metadata_cache_driver:
                    type: pool
                    id: doctrine.system_cache_pool
                query_cache_driver:
                    type: pool
                    id: doctrine.system_cache_pool
                result_cache_driver:
                    type: pool
                    id: doctrine.result_cache_pool

services:
    doctrine.result_cache_provider:
        class: Doctrine\Common\Cache\Psr6\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.result_cache_pool'
    doctrine.system_cache_provider:
        class: Doctrine\Common\Cache\Psr6\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.system_cache_pool'

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
