app:
    resource: "../../src/App/Controller/"
    type:     annotation
    prefix:   /

salt_site:
    resource: "@SaltSiteBundle/Controller/"
    type:     annotation
    prefix:   /

github_files:
    resource: "@GithubFilesBundle/Controller/"
    type:     annotation
    prefix:   /

salt_user:
    resource: "@SaltUserBundle/Controller/"
    type:     annotation
    prefix:   /

cftf:
    resource: "@CftfBundle/Controller/"
    type:     annotation
    prefix:   /

al_swagger_ui:
    resource: "@ALSwaggerUIBundle/Resources/config/routing.yml"
    prefix: /api/doc

al_swagger_ui_static_resources:
    resource: "@ALSwaggerUIBundle/Resources/config/static_resources_routing.yml"
    prefix: /api/swagger

logout:
    path: /logout

