salt_site:
    resource: "@SaltSiteBundle/Controller/"
    type:     annotation
    prefix:   /

github_files:
    resource: "@GithubFilesBundle/Controller/"
    type:     annotation
    prefix:   /

salt_user:
    resource: "@SaltUserBundle/Controller/"
    type:     annotation
    prefix:   /

cftf_util:
    resource: "@CftfUtilBundle/Controller/"
    type:     annotation
    prefix:   /

cftf_cms:
    resource: "@CftfCmsBundle/Controller/"
    type:     annotation
    prefix:   /

cftf_sbac:
    resource: "@CftfSbacBundle/Controller/"
    type:     annotation
    prefix:   /

cftf_ims:
    resource: "@CftfImsBundle/Controller/"
    type:     annotation
    prefix:   /

cftf_asn:
    resource: "@CftfAsnBundle/Controller/"
    type:     annotation
    prefix:   /

cftf:
    resource: "@CftfBundle/Controller/"
    type:     annotation
    prefix:   /

al_swagger_ui:
    resource: "@ALSwaggerUIBundle/Resources/config/routing.yml"
    prefix: /api/doc

al_swagger_ui_static_resources:
    resource: "@ALSwaggerUIBundle/Resources/config/static_resources_routing.yml"
    prefix: /api/swagger

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

logout:
    path: /logout

