parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   'pdo_mysql'
                #url: '%env(resolve:DATABASE_URL)%'
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                options:  '%pdo_options%'
                charset:  utf8mb4
                schema_filter: ~^(?!(cache_items|LearningStandards|std_*|map_*|grade_level))~
                server_version: 8.0.29
                mapping_types:
                    json: string
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
        types:
            json: App\Doctrine\Types\JsonType
            datetime: App\Doctrine\Types\DateTimeType
        #mapping_types:
        #    json: string
        #    uuid: char(36)
    orm:
        auto_generate_proxy_classes: true

        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                #metadata_cache_driver: apc
                #query_cache_driver: apc
                report_fields_where_declared: true
                second_level_cache:
                    enabled: false
                    log_enabled: true
                mappings:
                    App:
                        prefix: App\Entity
                        dir: "%kernel.project_dir%/src/Entity"
                        is_bundle: false
                    GedmoTree:
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
                        #alias: GedmoTree # (optional) it will default to the name set for the mapping
                        is_bundle: false
