# see https://symfony.com/doc/current/reference/configuration/framework.html
parameters:
    # Trust private ip space as well as current cloudflare IPs
    env(TRUSTED_PROXIES): '127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22'

framework:
    secret: '%secret%'
    csrf_protection: true
    http_method_override: true
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']

    # Defaults to true in Symfony 7, was false in 6
    handle_all_throwables: true

    # Annotations are deprecated and will be removed in Symfony 7
    annotations:
        enabled: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        # handler_id set to null will use default session handler from php.ini
        #handler_id:  ~
        handler_id:  session.handler.pdo
        #handler_id:  nelmio_security.session.handler
        #save_path:   "%kernel.project_dir%/var/sessions/%kernel.environment%"
        name: session
        cookie_lifetime: 0
        #cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: lax
        gc_maxlifetime: 86400
        gc_probability: 25
        gc_divisor:     100
        metadata_update_threshold: 120
        storage_factory_id: session.storage.factory.native
    esi: true
    fragments: true
    php_errors:
        log: true

    router:
      utf8: true

    request:
      formats:
        jsonld: 'application/ld+json'
        opensalt: 'application/vnd.opensalt+json'
        jsonapi: 'application/vnd.api+json'
        csv: ['text/csv', 'text/plain']
        ndjson: 'application/x-ndjson'

    assets:
        version: '%assets_version%'
        packages:
          encore:
            json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

    rate_limiter:
        excel_download:
            policy: 'sliding_window'
            limit: 3
            interval: '10 minutes'
