# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_USER: []
        ROLE_EDITOR: [ROLE_USER]
        ROLE_ADMIN: [ROLE_EDITOR]
        ROLE_SUPER_EDITOR: [ROLE_EDITOR]
        ROLE_SUPER_USER: [ROLE_ADMIN, ROLE_SUPER_EDITOR, ROLE_ALLOWED_TO_SWITCH]

    password_hashers:
        App\Entity\User\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        local_db_provider:
            entity:
                class: App\Entity\User\User

        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            stateless: true

        session_check:
            pattern: ^/session/check
            methods: [GET]
            security: false
            stateless: true

        read_api:
            pattern: ^/api/
            methods: [GET]
            security: false
            stateless: true

        main:
            pattern: ^/
            #lazy: true
            #stateless: true
            provider: local_db_provider
            user_checker: App\Security\UserChecker

            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
                default_target_path: /
                #always_use_default_target_path: true

            logout:
                path: /logout
                target: salt_index

            custom_authenticators:
                - App\Security\LoginFormAuthenticator

            entry_point: App\Security\LoginFormAuthenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.htm
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/2fa, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/, allow_if: "not is_granted('IS_AUTHENTICATED_2FA_IN_PROGRESS')" }
